### ISSUE TITLE
home: выбор из списка в мобильной версии

### ISSUE THREAD

**Issue by antonreshetnikov** [SilentImp/VacayKit#16]
при клику по выпадающему списку "i'm travelling to" в мобильной версии страница скролиться на верх и зумится. 

Происходит только в мобильном сафари на iphone, в хроме не воспроизводится.

**Comment by SilentImp** [comment]
Скрол вверх — поправил. Это был баг. 
Зум — не баг, это нормальное поведение. 
Заблокировать его можно только запретив пользователю зумить вообще. 
Сделал это конкретно на лендинге, но подозреваю, что это скверная идея.
