### ISSUE TITLE
иконки соц сетей в футере

### ISSUE THREAD

**Issue by antonreshetnikov** [SilentImp/VacayKit#20]
Иконки соц сетей в футере не центрированы вертикально. То что они чуть меньше чем в макете - не проблема, но хотелось бы что-бы они были центрированы. 

![screen shot 2015-04-19 at 22 32 55](https://cloud.githubusercontent.com/assets/61111/7221267/1d52de28-e6e4-11e4-9420-219878d6d383.png)

На скриншоте: слева макет, справа страница в chrome

**Comment by SilentImp** [comment]
Cкриншоты из opera,chrome,ie под win и chrome под mac
Так ок?
Неточности из за того, что я перенес соц-иконки в веб-шрифт, так как они используются в футере и на странице about с разным цветом и пришлось бы дублировать. 
Можно сделать их svg или png — будет более точно, но с дублированием.

![screen shot 2015-04-20 at 10 26 56](https://cloud.githubusercontent.com/assets/217308/7226295/eb0f5036-e747-11e4-8772-53f04579d548.png)
![screen shot 2015-04-20 at 10 27 18](https://cloud.githubusercontent.com/assets/217308/7226294/eb0dbb72-e747-11e4-8723-206be0a84c80.png)
![screen shot 2015-04-20 at 10 27 39](https://cloud.githubusercontent.com/assets/217308/7226297/eb1244d0-e747-11e4-8b08-4202acec45c9.png)
![screen shot 2015-04-20 at 10 27 45](https://cloud.githubusercontent.com/assets/217308/7226296/eb112a8c-e747-11e4-9e9f-9c491420b865.png)
