### ISSUE TITLE
Размер блока items__header в мобильной версии страницы

### ISSUE THREAD

**Issue by antonreshetnikov** [SilentImp/VacayKit#3]
В мобильной версии страницы не меняется высота блока items__header
В соответсвии с макетом высота этого блока  должна быть 120 px вместо 180 px в двух остальных версиях. 

Так-же в мобильной версии размер фонта содержимого этого блока должен быть меньше.

**Comment by SilentImp** [comment]
fixed

**Comment by antonreshetnikov** [comment]
Ты уменьшил размер фонта названия активити, но не размер фонта подписи с колличеством айтемов (его тоже нужно сделать меньше)
