### ISSUE TITLE
Ссылка на товар

### ISSUE THREAD

**Issue by antonreshetnikov** [SilentImp/VacayKit#9]
На данный момент для каждого товара ссылкой является только надпись с ценой. 
Cделай пожалуйста так что-бы весь блок с товаром был одной ссылкой.
Под блоком я понимаю блок содержащий Фото, название, рейтинг, цену и логотип магазина.

Это нужно сделать и в десктопной и в мобильной версии.

**Comment by SilentImp** [comment]
Сейчас при скролинге товаров горизонтально у меня часто получается кликнуть вместо того что бы скролить.
